[strict-component-boundaries] Exclude fixtures folder
Shopify/eslint-plugin-shopify pull request #117
Opened 2018-07-19 18:34 UTC by alexandcote

Fix #116 

We now exclude the `fixtures` folder. Maybe we should exclude everything inside tests instead?

2018-07-19 20:36 UTC, cartogram reviewed
@alexandcote thanks for working on this! The test looks good, but what about adding a check for imports with `json` extensions instead? We are never going to want this rule to flag `json` imports because they will never be a component.

2018-07-19 20:36 UTC, cartogram commented on lib/rules/strict-component-boundaries.js
> +          ((hasAnotherComponentInPath(pathParts) && pathParts.length > 1) ||
`isANotFixtureDirectory` => `isNotAFixtureDirectory`

2018-07-20 19:17 UTC, alexandcote commented
Do we have any other file extensions that we want to exclude, `scss`, `json`, `svg`, etc.. ?

2018-07-21 11:24 UTC, cartogram approved these changes

2018-07-21 11:24 UTC, cartogram commented on lib/rules/strict-component-boundaries.js
> +function isASupportedFileType(pathParts) {
`isASupportedFileType` => `isSupportedFileType`

2018-07-21 11:24 UTC, cartogram commented on lib/rules/strict-component-boundaries.js
> +  const unSupportedType = ['.json', '.svg', '.scss'];
Unless there is a reason not to, just keep the `.json` for now.

2018-07-21 11:24 UTC, cartogram commented on tests/lib/rules/strict-component-boundaries.js
> +      code: `import someThing from '../NameOfTheQuery/mock-query.scss';`,
These are also bad practice so its weird to me they are `valid`. As I commented above, I think we just keep the `.json` one to allow for fixtures but I'd rather not loosen this rule more than needed.

2018-07-21 11:24 UTC, cartogram commented on lib/rules/strict-component-boundaries.js
> +          isASupportedFileType(pathParts) &&
`isASupportedFileType` => `isSupportedFileType`

2018-07-21 11:26 UTC, cartogram commented
@alexandcote LGTM, did you want to do a patch release?

2018-07-21 22:24 UTC, cartogram commented on lib/rules/strict-component-boundaries.js
> +  const unSupportedType = ['.json', '.svg', '.scss'];
On second thought, can you add `.graphql`

2018-07-22 03:14 UTC, lemonmade commented
IMO excluding the fixtures folder is more appropriate here. Some components could easily have assets we don’t want people reaching for (i.e., our emoji picker has a json file for th emoji definition; components have their own private sass files, etc)

2018-07-22 22:24 UTC, cartogram commented
@lemonmade okay, that makes sense to me... didn't realize there were other places where we would be storing `json` next to a component.

2018-07-25 14:23 UTC, alexandcote commented
@lemonmade / @cartogram 👀

2018-07-25 14:34 UTC, lemonmade requested changes

2018-07-25 14:34 UTC, lemonmade commented on lib/rules/strict-component-boundaries.js
> +  return Boolean(pathParts.filter((part) => part === 'fixtures').length === 0);
No need for the `Boolean()`

2018-07-25 14:34 UTC, lemonmade commented on tests/lib/rules/strict-component-boundaries.js
> +      code: `import someThing from '../OtherComponent/fixtures/mock-query.json';`,
I still think this should be caught, but `../fixtures/OtherComponent/foo.json` should not (this means reaching up into another component, and getting its fixture, which doesn't seem right).

2018-07-25 22:25 UTC, alexandcote commented
Ok, I dig more into this and I found a lot of issue with this rules.

1. We should probably be able to include everything from an external library like:
```
import {Subscription} from 'apollo-client/util/Observable';
```
This trigger a lint error because `Observable` is PascalCase.

2. You may need a folder in the GraphQL folder to structure your queries: 
```
import something from '../graphql/SomeMockQuery/Query.graphql'
```

3. Tests can need child component:
```
import MyComponent from '../components/MyComponent'
import MyComponent from '../components/MyComponent/MyComponent'
```

4. You may need types from another component : 
```
import {MyType} from 'components/MyComponent/types'
import {MyType} from '../MyComponent/types'
```

5. You may need types from a graphql query of another component : 
```
import {MyType} from 'components/MyComponent/types'
```

6. You may prefer to use the absolute path:
```
sections/MyComponent/MyComponent.tsx

import {MyComponent} from 'sections/MyComponent/components'
```

I only list some of them. I think it will be really hard to handle all those case.
So my question is what we really want to prevent with `strict-component-boundaries`

2018-07-25 23:58 UTC, cartogram commented
@alexandcote We want to prevent all of those except the first one.

2018-07-26 18:12 UTC, lemonmade commented
We should actually be able to solve the first one, too. Using `resolve` from the `eslint-module-utils` package to get the fully resolved path for a module (see [example](https://github.com/Shopify/eslint-plugin-shopify/blob/master/lib/utilities.js#L42)). That will let us tell if it is in node modules or part of the real project.

2018-08-02 19:04 UTC, cartogram commented
@alexandcote let me know if you need help wrapping this up.

2018-08-15 14:13 UTC, alexandcote commented
Ready for 👀

2018-08-21 21:02 UTC, cartogram commented
@alexandcote additions LGTM. 🚢

2018-08-21 21:38 UTC, merged