[WIP] Adds `no-namespaced-import` rule
Shopify/eslint-plugin-shopify pull request #262
Opened 2019-05-12 20:54 UTC by cartogram

2019-05-13 20:08 UTC, GoodForOneFare commented
Approach LGTM.

2019-06-14 19:22 UTC, lemonmade requested changes

2019-06-14 19:22 UTC, lemonmade commented on docs/rules/no-namespace-imports.md
> +Namespace imports grab all exported variables from a module as nested properties under a single variable name. This approach of importing everything, rather than only what is required from the module
It does not polite the local scope, that's half the benefit of namespace imports. If we're going to sell this on anything, it should be that this style of import breaks tree shaking.

2019-06-14 19:22 UTC, lemonmade commented on docs/rules/no-namespace-imports.md
> +import React from 'react';
I'd rather show an example showing named imports > namespace import. Yes, this rule does help us enforce the right style for React, but that's something that could conceivably be addressed in types instead.

2019-06-14 19:22 UTC, lemonmade commented on docs/rules/no-namespace-imports.md
> +      "allow": ["react", "some-custom-module"]
Probably best not to show it for React, we'd never want them to do that, would we?

2019-06-14 19:22 UTC, lemonmade commented on lib/rules/no-namespace-imports.js
> +        fix: (fixer) => {
I don't think it's safe to provide a fixer, we have no idea what members they reference, and turning it into a default import is not going to be correct in many cases.

2019-06-14 19:22 UTC, lemonmade commented on lib/rules/no-namespace-imports.js
> +    const regex = new RegExp(stringOrRegex);
Better to construct this regex array upfront.

2019-06-17 18:17 UTC, cartogram commented
superseded by https://github.com/Shopify/eslint-plugin-shopify/pull/305

2019-06-22 16:02 UTC, cartogram commented
After trying the import/no-namespace rule, I do think we want a custom rule after all. I'll continue with this work and get it ready for another review.

2019-11-14 08:49 UTC, merged