Support arrow functions in react-no-multiple-render-methods
Shopify/eslint-plugin-shopify pull request #498
Opened 2019-12-04 16:32 UTC by vhpoet

Title is self explanatory.

2019-12-04 16:35 UTC, GoodForOneFare commented
Thanks for the contribution, Vahe! ❤️ @cartogram could you take a look when you have a moment, please?

2019-12-05 01:50 UTC, cartogram commented
@vhpoet do mind adding a test for this?

2019-12-05 02:08 UTC, cartogram requested changes
Thanks for this contribution! Will take a look again once these changes are in 🙂

2019-12-05 02:08 UTC, cartogram commented on lib/rules/react-no-multiple-render-methods.js
> +  const name = (node.key && node.key.name) || (node.parent && node.parent.key && node.parent.key.name);
let's break this out into a small utility function. Something like:
```
getMethodName(node) {
  if (node.key) {
     return node.key.name
  }

  return node.parent && node.parent.key && node.parent.key.name;
}
```

2019-12-05 02:08 UTC, cartogram commented on lib/rules/react-no-multiple-render-methods.js
> +      ArrowFunctionExpression(node) {
You are going to need to add a few tests for this. At the least I'd like to see it catch something like:
```
      code: `class Button extends React.Component {
        renderArrowFunction = () => {}
        renderBar = () => {}
        render() {}`
```

I think the error type will be different for these, so you will also need to modify the `error` utility to accept a `type` argument. Something like:

```
function error(memberName, type = 'MethodDefinition') {
  return {
    type,
    message: `Don’t use multiple render methods in a single component; they generally make your component harder to read. Instead break ${memberName} out into its own component and render it inside this one.`,
  };
}
```
then you should be able to do the following for the error of the above snippet:
```
errors: [
  error('renderArrowFunction', 'ArrowFunctionExpression'),
  error('renderBar', 'ArrowFunctionExpression'),
],
```

Happy to clarify anything you need.

2020-03-25 16:30 UTC, alexandcote commented
I did the rework you asked @cartogram. Let me know if everything is 👍🏼.

Thanks again @vhpoet 🤟🏼

2020-03-25 16:44 UTC, BPScott approved these changes
Not tried this but the test LGTM

2020-03-25 16:45 UTC, merged